name: Add issues to Data Sources team project
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: get-github-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: grafana-oss-big-tent
      - name: Add to project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/grafana/projects/1085
          github-token: ${{ steps.get-github-token.outputs.token }}
