name: Run commands when issues are labeled

permissions:
  contents: read

on:
  issues:
    types: [labeled]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{secrets.ISSUE_COMMANDS_TOKEN}}
          configPath: issue_commands
