name: Plugins - CD
run-name: Deploy ${{ inputs.branch }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch or tag to publish from. Can be used to deploy PRs to dev
        default: main
      environment:
        description: Environment to publish to
        required: true
        type: choice
        options:
          - 'dev'
          - 'ops'
          - 'prod-canary'
          - 'prod'
      docs-only:
        description: Only publish docs, do not publish the plugin
        default: false
        type: boolean

permissions: {}

jobs:
  cd:
    name: CD
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@ci-cd-workflows/v10.1.0
    permissions:
      contents: write
      pull-requests: read
      id-token: write
      attestations: write
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
      docs-only: ${{ fromJSON(github.event.inputs.docs-only) }}
      # Scope for the plugin when publishing it to the catalog.
      # Choose between:
      # - 'universal': on-prem + cloud (default)
      # - 'grafana_cloud': cloud only, hidden for on-prem users
      scopes: grafana_cloud
      github-draft-release: false
      release-reference-regex: (main)|(v\d+\.\d+\.\d+)
